[package]
name = "fastchallange"
version = "0.1.0"
edition = "2024"

[features]
log_chunk_update = []

[dependencies]
wgpu = "29"
winit = "0.30"
raw-window-handle = "0.6.2"
env_logger = "0.11.10"
pollster = "0.4.0"
log = "0.4.33"
bytemuck = "1.25.0"
glam = { version = "0.33.1", features = ["bytemuck"] }
rustc-hash = "2.1.2"
fastnoise2 = "0.4.0"
rayon = "1.12.0"
egui = "0.35"
egui-wgpu = "0.35"
egui-winit = "0.35"
gltf = { version = "1.4", features = ["import"] }
anyhow = "1.0.103"
